### Teste Torre API - Search Jobs

POST https://search.torre.co/opportunities/_search
Content-Type: application/json

{
  "id": { "term": "developer" },
  "offset": 0,
  "limit": 10,
  "membersCloseConnections": false,
  "penalizeOverqualified": false
}




### 🧬 Search for a user's genome


POST https://search.torre.co/opportunities/_search
Content-Type: application/json

{
  "id": {
    "term": "developer"
  },
  "membersCloseConnections": false,
  "penalizeOverqualified": false
}


### 🧬 Search for a user's genome
GET http://localhost:3001/api/torre/genome/renanpeixotox

### 🧬 Search for a user's genome
GET http://localhost:3001/api/torre/genome/thalleslima


### Save favorite
POST http://localhost:3001/api/torre/favorites
Content-Type: application/json

{
  "userId": "user12334",
  "itemId": "vaga123",
  "type": "job",
  "data": {
    "title": "Desenvolvedor Backend",
    "location": "Remoto"
  }
}


### Search analytics

GET http://localhost:3001/api/torre/analytics


### ❌ Genome with invalid username (expect error)

GET http://localhost:3001/api/torre/genome/usuarioinexistente123

