### Teste Torre API - Search Jobs

POST https://search.torre.co/opportunities/_search
Content-Type: application/json

{
  "id": { "term": "developer" },
  "offset": 0,
  "limit": 10,
  "membersCloseConnections": false,
  "penalizeOverqualified": false
}




### 🧬 Search for a user's opportunities


POST https://search.torre.co/opportunities/_search
Content-Type: application/json

{
  "id": {
    "term": "developer"
  },
  "membersCloseConnections": false,
  "penalizeOverqualified": false
}


### 🧬 Search for a user's genome
GET http://localhost:3001/api/torre/genome/renanpeixotox

### 🧬 Search for a user's genome
GET http://localhost:3001/api/torre/genome/thalleslima


### Save favorite
POST http://localhost:3001/api/torre/favorites
Content-Type: application/json

{
  "userId": "user1232d3G33144",
  "itemId": "vaga123",
  "type": "job",
  "data": {
    "title": "Desenvolvedor Backend",
    "location": "Remoto"
  }
}


### Search analytics

GET http://localhost:3001/api/torre/analytics


### ❌ Genome with invalid username (expect error)

GET http://localhost:3001/api/torre/genome/usuarioinexistente123


###
POST https://torre-engineering-test-technician.onrender.com/api/torre/search
Content-Type: application/json

{
  "criteria": {
    "text": "developer"
  },
  "limit": 5
}

### limit api
curl http://localhost:3001/api/torre/analytics?limit=5



### 📊 Analytics
GET http://localhost:3001/api/torre/analytics


### 🗑️ Delete Favorite
DELETE http://localhost:3001/api/torre/favorites/665fe4573a0b66b3d71d1f88

###
GET http://localhost:3001/api/health
###
GET http://localhost:3001/api/version
###
curl -H "Accept-Language: en" http://localhost:3001/api/torre/favorites
